### ISSUE TITLE
Últimas mejoras

### ISSUE THREAD

**Issue by abelespana** [abelespana/marble#7]
- [ ] Darle vidilla al header (nuevo fondo)
- [ ] Quitar los videos del registro y demás (antes me molaban pero ahora me parecen horrorosos)
- [ ] ¿Migrar el footer del proyecto versión Angular?
- [ ] Aplicar algún efecto chulo en la creación de un post (un _fadeIn_  y un mostrar/ocultar mismamente)
- [ ] Sería ideal --> Instanciar un objeto de clase _User_ cuando completo el proceso de registro. **Rober**
- [ ] Bonus track --> todo lo del punto anterior y encima muestro los datos en una ventana modal de confirmación **Rober**
- [ ] Engancharse a una BBDD de Mongo y pedir los datos de nuestros usuarios de ella a través de Node (difícil, but...)
- [ ] Más cosas molonas y fáciles de implantar que se nos ocurran esta noche.

**Comment by blazama** [comment]
buajajajajajajja
    En viernes, 28 de septiembre de 2018 15:44:19 CEST, Abel España <notifications@github.com> escribió:  
 
 
Closed #7.
